package core

import (
	"bytes"
	"fmt"
	"go/format"
	"os"
	"strings"
	"testing"
	"time"
)

const updateTimestampFormatCasesEnv = "NERDLOG_UPDATE_TIMESTAMP_FORMAT_CASES"

// TestUpdateTimestampFormatCases regenerates timestamp_format_cases_data_test.go
// when running "make update-test-expectations". It is opt-in so ordinary tests
// compare against a stable, illustrative table, and behavior changes remain
// explicit in the generated-file diff.
func TestUpdateTimestampFormatCases(t *testing.T) {
	if os.Getenv(updateTimestampFormatCasesEnv) == "" {
		t.Skipf("set %s=1 to regenerate timestamp format cases", updateTimestampFormatCasesEnv)
	}

	type variant struct {
		name          string
		fraction      string
		bracketed     bool
		startFieldIdx int
		attached      bool
	}
	secondVariants := []variant{
		{name: "plain/no-fraction/field-0/separated"},
		{name: "bracketed/no-fraction/field-3/attached", bracketed: true, startFieldIdx: 3, attached: true},
		{name: "plain/no-fraction/field-3/separated", startFieldIdx: 3},
		{name: "bracketed/milliseconds/field-0/separated", fraction: "05.000", bracketed: true},
		{name: "plain/milliseconds/field-3/attached", fraction: "05.000", startFieldIdx: 3, attached: true},
		{name: "bracketed/microseconds/field-3/separated", fraction: "05.000000", bracketed: true, startFieldIdx: 3},
		{name: "plain/microseconds/field-0/attached", fraction: "05.000000", attached: true},
		{name: "bracketed/microseconds/field-0/attached", fraction: "05.000000", bracketed: true, attached: true},
		{name: "plain/comma-microseconds/field-0/separated", fraction: "05,000000"},
	}
	nonSecondVariants := []variant{
		{name: "plain/field-0/separated"},
		{name: "bracketed/field-3/attached", bracketed: true, startFieldIdx: 3, attached: true},
		{name: "plain/field-3/attached", startFieldIdx: 3, attached: true},
		{name: "bracketed/field-0/separated", bracketed: true},
	}

	firstSampleTime := time.Date(2025, 9, 8, 8, 9, 10, 123456000, time.UTC)
	lastSampleTime := time.Date(2025, 11, 18, 23, 57, 56, 901234000, time.UTC)
	var output bytes.Buffer
	output.WriteString("// Code generated by \"make update-test-expectations\"; DO NOT EDIT.\n")
	output.WriteString("// The table is intentionally explicit and independent of knownTimestampLayouts.\n\n")
	output.WriteString("package core\n\n")
	output.WriteString("var timestampFormatCases = []timestampFormatCase{\n")

	for _, canonicalLayout := range knownTimestampLayouts {
		variants := nonSecondVariants
		if strings.Contains(canonicalLayout, "05") {
			variants = secondVariants
		}
		for _, v := range variants {
			layout := canonicalLayout
			if v.fraction != "" {
				layout = strings.Replace(layout, "05", v.fraction, 1)
			}
			if v.bracketed {
				layout = "[" + layout + "]"
			}

			format := TimestampFormat{
				Layout:           layout,
				StartFieldIdx:    v.startFieldIdx,
				HasTrailingChars: v.attached,
			}
			detectedFormat, agentErr := inferTimestampFormatFixture(format, firstSampleTime, lastSampleTime)
			descriptorFormat := format
			if detectedFormat != nil {
				descriptorFormat = *detectedFormat
			}
			descr, descrErr := GenerateTimeDescr(descriptorFormat)

			fmt.Fprintf(&output, "\t{\n")
			fmt.Fprintf(&output, "\t\tname: %q,\n", canonicalLayout+"/"+v.name)
			fmt.Fprintf(&output, "\t\tcanonicalLayout: %q,\n", canonicalLayout)
			fmt.Fprintf(&output, "\t\tformat: TimestampFormat{Layout: %q, StartFieldIdx: %d, HasTrailingChars: %t},\n", format.Layout, format.StartFieldIdx, format.HasTrailingChars)
			if detectedFormat != nil && *detectedFormat != format {
				fmt.Fprintf(
					&output,
					"\t\twantDetectedFormatOverride: &TimestampFormat{Layout: %q, StartFieldIdx: %d, StartSubstrOffset: %d, HasTrailingChars: %t},\n",
					detectedFormat.Layout,
					detectedFormat.StartFieldIdx,
					detectedFormat.StartSubstrOffset,
					detectedFormat.HasTrailingChars,
				)
			}
			if descrErr != nil {
				fmt.Fprintf(&output, "\t\twantErr: %q,\n", descrErr.Error())
			} else {
				fmt.Fprintf(&output, "\t\twantMinuteKeyLayout: %q,\n", descr.MinuteKeyLayout)
				output.WriteString("\t\twantAWK: TimeFormatAWKExpr{\n")
				fmt.Fprintf(&output, "\t\t\tMonth: %s,\n", timestampFormatRawString(t, descr.AWKExpr.Month))
				fmt.Fprintf(&output, "\t\t\tYear: %s,\n", timestampFormatRawString(t, descr.AWKExpr.Year))
				fmt.Fprintf(&output, "\t\t\tDay: %s,\n", timestampFormatRawString(t, descr.AWKExpr.Day))
				fmt.Fprintf(&output, "\t\t\tHHMM: %s,\n", timestampFormatRawString(t, descr.AWKExpr.HHMM))
				fmt.Fprintf(&output, "\t\t\tMinuteKey: %s,\n", timestampFormatRawString(t, descr.AWKExpr.MinuteKey))
				fmt.Fprintf(&output, "\t\t\tTimezone: %s,\n", timestampFormatRawString(t, descr.AWKExpr.Timezone))
				output.WriteString("\t\t},\n")
			}
			if agentErr != "" {
				fmt.Fprintf(&output, "\t\twantAgentErr: %q,\n", agentErr)
			}
			output.WriteString("\t},\n")
		}
	}
	output.WriteString("}\n")

	formatted, err := format.Source(output.Bytes())
	if err != nil {
		t.Fatalf("format generated timestamp cases: %v", err)
	}
	if err := os.WriteFile("timestamp_format_cases_data_test.go", formatted, 0644); err != nil {
		t.Fatalf("write generated timestamp cases: %v", err)
	}
}

func timestampFormatRawString(t *testing.T, value string) string {
	t.Helper()
	if strings.ContainsRune(value, '`') {
		t.Fatalf("AWK expression contains a backtick and cannot be emitted as a raw string: %q", value)
	}
	return "`" + value + "`"
}

func inferTimestampFormatFixture(format TimestampFormat, first, last time.Time) (*TimestampFormat, string) {
	line := func(input time.Time, suffix string) string {
		layout := strings.ReplaceAll(format.Layout, ".999999", ".000000")
		separator := " "
		if format.HasTrailingChars {
			separator = ""
		}
		return strings.Repeat("before ", format.StartFieldIdx) + input.Format(layout) + separator + suffix
	}

	// Bootstrap samples from the end of the file first.
	descr, err := InferTimeFormatDescr("syslog", []string{
		line(last, "myhost app[123]: message twelve"),
		line(first, "myhost app[123]: message one"),
	})
	if err != nil {
		return nil, err.Error()
	}
	inferredFormat := descr.TimestampFormat.TimestampFormat
	return &inferredFormat, ""
}
